### ISSUE TITLE
Optics: Nature and Propagation of Light - Reflection and Refraction

### ISSUE THREAD

**Issue by LaverBen** [LaverBen/physics-toolkit#4]
# Optics: Nature and Propagation of Light - Reflection and Refraction

### Breakdown
* When a ray strikes a smooth interface it is partly reflected and partly refracted
* Refraction is described with index of refraction, calculated using the speed of light in the material
* There are laws of reflection and refraction determining these effects
* Refraction and reflection follow a reversible path
* Intensity of light reflected and refracted depend on the angle of incidence, two indices of refraction and polarisation of the ray
  + This can be predicted from Maxwell's equations
  + This leads to Fresnel's equations
  + This can also derive Brewster's angle
* Index of refraction also depends on wavelength of light (an effect called dispersion)
* Frequency does not change when passing from one material to another
* Wavelength must therefore change when the wave speed changes in a new material as the wave speed is dependent on wavelength and frequency. Index of refraction can be used to calculate the change in wavelength
* Corner reflectors (made of three mirrors forming the corner of a cube) will reverse the direction component of an incident ray in one plane only

## Tasks
* [x] Law of reflection calculator
* [ ] Demonstrate a corner reflector using law of reflection calculator
  + [ ] Create `Ray` object
  + [ ] Create `ReflectivePlane` object
  + [ ] Make test checking that a ray incident on a corner constructed from 3 reflective planes meeting at a right angle will be reflected back in the opposite direction of incidence (in only one axis)
* [ ] Law of refraction (Snell's law)
* [ ] Use both calculators to prove reflection and refraction are reversible
* [ ] Fresnel's equations calculator
* [ ] Brewster's angle finder
* [ ] Refraction wavelength calculator
* [ ] Use refraction wavelength calculator to demonstrate dispersion
